### ISSUE TITLE
Index out of range for CSS Select

### ISSUE THREAD

**Issue by sebastian9er** [karan/TPB#84]
I am getting the following error when running the example script from the project site (here: https://github.com/karan/TPB#usage):

  File "example.py", line 34, in <module>
    print(torrent.info)
  File "/usr/local/lib/python2.7/dist-packages/ThePirateBay-v1.3.5-py2.7.egg/tpb/tpb.py", line 347, in info
    info = root.cssselect('#details > .nfo > pre')[0].text_content()
IndexError: list index out of range

The only change I made, was replacing the domain from "https://thepiratebay.org" to "https://thepiratebay.la"

**Comment by sebastian9er** [comment]
I made a duplicate without noticing...

**Comment by ah3243** [comment]
i'm getting the same error could you provide any more details about where the duplicate was?

**Comment by sebastian9er** [comment]
To be honest, I have no idea. At the time of writing it was a duplicate, but I don't know if the issue was resolved, closed or deleted. Sorry!
